"""datetime column to orders

Revision ID: 482ff7c0a44c
Revises: 0a6484c25c45
Create Date: 2026-02-01 18:39:52.958970

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "482ff7c0a44c"
down_revision: Union[str, Sequence[str], None] = "0a6484c25c45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders", sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "created_at")
    # ### end Alembic commands ###
